### PR TITLE
Fix scanner deconstruction

### LINKED ISSUE #241: Flaky ScannerAPITests.shouldIgnoreMonitoringFrameOfFormerScanRound test
### Commit
b3be1da Increase readability of integration tests (#234)

### Steps to reproduce
How can the issue/bug be reproduced?
1. colcon build
2. `./build/psen_scan_v2/devel/lib/psen_scan_v2/integrationtest_scanner_api --gtest_repeat=1000 --gtest_break_on_failure --gtest_filter=ScannerAPITests.shouldIgnoreMonitoringFrameOfFormerScanRound`

### Expected behavior
Should succeed every time

### Observed behavior
Segmentation fault every once in a while
```
MockUDPServer: Data successfully send
ScannerMock: Send monitoring frame...
ScannerMock: Send monitoring frame...
MockUDPServer: Data successfully send
MockUDPServer: Data successfully send
Debug:   Scanner: Destruction called.
Debug:   StateMachine: Exiting state: WaitForMonitoringFrame
Debug:   StateMachine: Action: handleMonitoringFrame
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

### PR DESCRIPTION
**Pull request by rfeistenauer**
## Description

These changes Fix #241 by changing the scanner deconstruction.

These changes solve the problem since:

- `stop()` on the state machine does not prevent further `process_event` thus it is better to transition into the defined `Stop`-State. I.e. we (currently) always require a call to `ScannerV2::stop()`. To avoid receiving more messages the `io_service` needed to be stopped(). It seems that going into destruction while receiving messages which are redirected to `handleReceiveMessage` is a bad idea...
- Inside the tests the member order the mock is put at the end so that is gets destroyed first. This in combination with the above seems to stabilize the test.

---

<details>
<summary>PR Checklist</summary>

### Things to add, update or check by the maintainers before this PR can be merged.

- [x] ~Public api function documentation~
- [x] ~Architecture documentation reflects actual code structure~
- [x] ~[Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)~
- [x] ~Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)~
- [x] ~Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))~
- [x] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [x] CHANGELOG.rst updated
- [x] ~Copyright headers~
- [x] ~Examples~

### Review Checklist
- [x] ~Soft- and hardware architecture (diagrams and description)~
- [x] Test review (test plan and individual test cases)
- [x] ~Documentation describes purpose of file(s) and responsibilities~
- [x] Code (coding rules, style guide)

### Release planning (please answer)
- [x] ~When is the new feature released?~
- [x] ~Which dependent packages do have to be released simultaneously?~

### Hardware tests
_Unstrike the text below to enable automatic hardware tests if available. Otherwise use this as a request for the reviewer._
- [x] Perform hardware tests

</details>

### CODE REVIEW

File: standalone/test/integration_tests/api/integrationtest_scanner_api.cpp [hunk 1]
```diff
@@ -312,17 +315,17 @@ TEST_F(ScannerAPITests, testStartReplyTimeout)
   util::Barrier twice_called_barrier;
   {
     InSequence seq;
-    EXPECT_CALL(*scanner_mock_, receiveControlMsg(_, _)).Times(1);
```
Comment (agutenkunst) [inline standalone/test/integration_tests/api/integrationtest_scanner_api.cpp:315]: Please put this in a separate PR
