### PR TITLE
Prevent error when diagnostics is disabled. Fix #294

### LINKED ISSUE #294: Laserscan Callback not invoked when diagnostics disabled
### Commit
Introduced by 7289f21

### Steps to reproduce
Build standalone app and execute it.

### Expected behavior
No errors and throttled output of scans.

### Log
```
Error:   StateMachine: Diagnostic messages not set! (Contact PILZ support if the error persists.)
         at line 186 in /home/imartini/ros_ws/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
Error:   StateMachine: Diagnostic messages not set! (Contact PILZ support if the error persists.)
         at line 186 in /home/imartini/ros_ws/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
Error:   StateMachine: Diagnostic messages not set! (Contact PILZ support if the error persists.)
         at line 186 in /home/imartini/ros_ws/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
...
```

### PR DESCRIPTION
**Pull request by martiniil**
## Description

* Fix #294
* Increase timeout in test of monitoring-frame timeout (due to rare ci failure, see below)

<details>
<summary>Log (windows standalone ci)</summary>

```
  [ RUN      ] ScannerAPITestsDefaultSetUp.shouldShowUserMsgIfMonitoringFrameReceiveTimeout
  Host ports:
  - data port = 45012
  - control port = 57012
  Scanner ports:
  - data port = 3012
  - control port = 7012
  
  Debug:   StateMachine: Entering state: Idle
  ScannerMock: Send start reply...
  MockUDPServer: Data successfully send
  ScannerMock: Send stop reply...
  MockUDPServer: Data successfully send
D:\a\psen_scan_v2\psen_scan_v2\standalone\test\integration_tests\api\integrationtest_scanner_api.cpp(407): error : Actual function call count doesn't match EXPECT_CALL(mock, log("StateMachine: Timeout while waiting for MonitoringFrame message." " (Please check the ethernet connection or contact PILZ support if the error persists.)", console_bridge::CONSOLE_BRIDGE_LOG_WARN, ::testing::_, ::testing::_))... [D:\a\psen_scan_v2\psen_scan_v2\standalone\build\RUN_TESTS.vcxproj]
           Expected: to be called once
             Actual: never called - unsatisfied and active
  Debug:   Scanner: Destruction called.
  Debug:   StateMachine: Exiting state: Stopped
  [  FAILED  ] ScannerAPITestsDefaultSetUp.shouldShowUserMsgIfMonitoringFrameReceiveTimeout (2004 ms)
```
</details>

---

<details>
<summary>PR Checklist</summary>

### Things to add, update or check by the maintainers before this PR can be merged.

- [x] ~Public api function documentation~
- [x] ~Architecture documentation reflects actual code structure~
- [x] ~[Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)~
- [x] ~Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)~
- [x] ~Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))~
- [x] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [x] CHANGELOG.rst updated
- [x] Copyright headers
- [x] Examples

### Review Checklist
- [x] Soft- and hardware architecture (diagrams and description)
- [ ] Test review (test plan and individual test cases)
- [x] Documentation describes purpose of file(s) and responsibilities
- [ ] Code (coding rules, style guide)

### Release planning (please answer)
- [x] When is the new feature released? ASAP
- [x] Which dependent packages do have to be released simultaneously? NONE

### Hardware tests
- [ ] Perform hardware tests

</details>

### CODE REVIEW

**Comment by martiniil** [comment]
Result of hardware tests: Two tests are unstable (as before) `hwtest_zoneset_switching` `hwtest_timestamp_standalone`, all others pass.

File: standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h [hunk 1]
```diff
@@ -70,15 +71,13 @@ static std::vector<double> generateIntensities(const unsigned int& num_elements,
   return vec;
 }
 
-static data_conversion_layer::monitoring_frame::Message
-createValidMonitoringFrameMsg(const uint32_t scan_counter = 42,
-                              const util::TenthOfDegree start_angle = DEFAULT_SCAN_RANGE.getStart(),
-                              const util::TenthOfDegree end_angle = DEFAULT_SCAN_RANGE.getEnd(),
-                              const uint8_t active_zoneset = 1)
+static data_conversion_layer::monitoring_frame::MessageBuilder
+prepareMinimalValidMonitoringFrameMsg(const util::TenthOfDegree start_angle = DEFAULT_SCAN_RANGE.getStart(),
```
Comment (cdoehn) [inline standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h:75]: As I understand the prefix "prepare" means the MessageBuilder will be returned and the prefix "create" the Message will be returned. I would consider to make this implicit knowlege explicit and rename prepareXXXXMonitoringFrameMsg to createXXXXMonitoringFrameMsgBuilder. 

On the oder hand I would consider to drop the "Valid" in the names for valid Message creators, because I think it is clear, that the message should be valid. But the "Invalid" I would keep in the names.

This comment relates also to other lines of code, not only this line.

**Review by cdoehn — APPROVED** [review]

**Comment by agutenkunst** [comment]
@PilzHardwareTestBot The first issue with `hw_tests/hwtest_zoneset_switching.cpp` should be resolved by https://github.com/PilzDE/psen_scan_v2/pull/297

I am not sure why the second one seems to fail to get data
